config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :customer_pets
  resources :schedules
  resources :doctors

  root 'appointments#index'

end

app/models/customer_pet.rb
class CustomerPet < ActiveRecord::Base
	self.inheritance_column = nil
	validates_length_of :name,  maximum: 35 
	validates_inclusion_of :type, in: %w( dog cat bird ), message: "extension %{value} is not included in the list"
	validates :breed, presence: true
	validates :age, presence: true
	validates :weight, presence: true
	validates :date, presence: true
end

app/controllers/customer_pets_controller.rb
class CustomerPetsController < ApplicationController
  before_action :set_customer_pet, only: [:show, :edit, :update, :destroy]

  # GET /customer_pets
  # GET /customer_pets.json
  def index
    @customer_pets = CustomerPet.all
  end

  # GET /customer_pets/1
  # GET /customer_pets/1.json
  def show
  end

  # GET /customer_pets/new
  def new
    @customer_pet = CustomerPet.new
  end

  # GET /customer_pets/1/edit
  def edit
  end

  # POST /customer_pets
  # POST /customer_pets.json
  def create
    @customer_pet = CustomerPet.new(customer_pet_params)

    respond_to do |format|
      if @customer_pet.save
        format.html { redirect_to @customer_pet, notice: 'Customer pet was successfully created.' }
        format.json { render :show, status: :created, location: @customer_pet }
      else
        format.html { render :new }
        format.json { render json: @customer_pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_pets/1
  # PATCH/PUT /customer_pets/1.json
  def update
    respond_to do |format|
      if @customer_pet.update(customer_pet_params)
        format.html { redirect_to @customer_pet, notice: 'Customer pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer_pet }
      else
        format.html { render :edit }
        format.json { render json: @customer_pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_pets/1
  # DELETE /customer_pets/1.json
  def destroy
    @customer_pet.destroy
    respond_to do |format|
      format.html { redirect_to customer_pets_url, notice: 'Customer pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_pet
      @customer_pet = CustomerPet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_pet_params
      params.require(:customer_pet).permit(:name, :type, :breed, :age, :weight, :date)
    end
end

app/helpers/customer_pets_helper.rb
module CustomerPetsHelper
end

app/views/customer_pets/_form.html.erb
<%= form_for(@customer_pet) do |f| %>
  <% if @customer_pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer_pet.errors.count, "error") %> prohibited this customer_pet from being saved:</h2>

      <ul>
      <% @customer_pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.text_field :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customer_pets/edit.html.erb
<h1>Editing Customer Pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer_pet %> |
<%= link_to 'Back', customer_pets_path %>

app/views/customer_pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customer Pets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Breed</th>
      <th>Age</th>
      <th>Weight</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer_pets.each do |customer_pet| %>
      <tr>
        <td><%= customer_pet.name %></td>
        <td><%= customer_pet.type %></td>
        <td><%= customer_pet.breed %></td>
        <td><%= customer_pet.age %></td>
        <td><%= customer_pet.weight %></td>
        <td><%= customer_pet.date %></td>
        <td><%= link_to 'Show', customer_pet %></td>
        <td><%= link_to 'Edit', edit_customer_pet_path(customer_pet) %></td>
        <td><%= link_to 'Destroy', customer_pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer pet', new_customer_pet_path %>

app/views/customer_pets/new.html.erb
<h1>New Customer Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', customer_pets_path %>

app/views/customer_pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer_pet.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @customer_pet.type %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @customer_pet.breed %>
</p>

<p>
  <strong>Age:</strong>
  <%= @customer_pet.age %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @customer_pet.weight %>
</p>

<p>
  <strong>Date:</strong>
  <%= @customer_pet.date %>
</p>

<%= link_to 'Edit', edit_customer_pet_path(@customer_pet) %> |
<%= link_to 'Back', customer_pets_path %>